In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import time
import datetime
import psutil
np.random.seed(42)
from sklearn.preprocessing import LabelEncoder
import random
random.random_state = 0
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

In [19]:
train = pd.read_csv('BPI Challenge 2017-training.csv')
test = pd.read_csv('BPI Challenge 2017-test.csv')
data = pd.concat([train, test])

In [20]:
# event shifting
data['next_event'] = data.groupby('case concept:name')['event concept:name'].shift(-1)
data["prev_event"] = data.groupby('case concept:name')['event concept:name'].shift(1)
data["prev_lifecycle"] = data.groupby('case concept:name')['event lifecycle:transition'].shift(1)

In [21]:
event_encoder = LabelEncoder()

In [22]:
def random_trace_split(data):

    test = data[data["case concept:name"].isin(random.sample(data["case concept:name"].tolist(), round(len(data["case concept:name"].unique())/8)))]

    train = data[~data["case concept:name"].isin(test["case concept:name"].unique())]

    labels_name = data["event concept:name"].unique()
    event_encoder.fit(labels_name)
    train[["event concept:name", "next_event", "prev_event"]] = train[["event concept:name", "next_event", "prev_event"]].apply(event_encoder.fit_transform)
    test[["event concept:name", "next_event", "prev_event"]] = test[["event concept:name", "next_event", "prev_event"]].apply(event_encoder.fit_transform)


    labels_lifecycle = data["event lifecycle:transition"].unique()
    event_encoder.fit(labels_lifecycle)
    train[["event lifecycle:transition", 'prev_lifecycle']] = train[["event lifecycle:transition", 'prev_lifecycle']].apply(event_encoder.fit_transform)
    test[["event lifecycle:transition", 'prev_lifecycle']] = test[["event lifecycle:transition", 'prev_lifecycle']].apply(event_encoder.fit_transform)

    X_test = test[[
#                    "case AMOUNT_REQ", 
                   "event concept:name", "prev_event", "event lifecycle:transition", 'prev_lifecycle']]
    y_test = test["next_event"].values

    X_train = train[[
#                     "case AMOUNT_REQ", 
                    "event concept:name", "prev_event", "event lifecycle:transition", 'prev_lifecycle']]
    y_train = train["next_event"].values
    return X_train, X_test, y_train, y_test

In [23]:
X_train, X_test, y_train, y_test = random_trace_split(data)

C:\Users\blaze\Anaconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [25]:
max_features = ['auto', 'log2']
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]
criterion = ['gini', 'entropy']
random_grid = {'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap,
               'criterion': criterion}

In [31]:
def evaluate(model, test_features, test_labels):
    y_pred = model.predict(X_test)
    prec_score = precision_score(y_test, y_pred, average="weighted", zero_division=0)
    rec_score = recall_score(y_test, y_pred, average="weighted", zero_division=0)
    F1_score = f1_score(y_test, y_pred, average="weighted", zero_division=0)
    acc_score = accuracy_score(y_test, y_pred)

    print(f'The accuracy of the model is {acc_score}.')
    print(f'The precision of the model is {prec_score}, using weighted average.')
    print(f'The recall of the model is {rec_score}, using weighted average.')
    print(f'The f1-score of the model is {F1_score}, using weighted average.')
    
    return acc_score



In [35]:
base_model = RandomForestClassifier(n_estimators=10,random_state=42)
base_model.fit(X_train, y_train)
base_accuracy = evaluate(base_model, X_train, y_train)

The accuracy of the model is 0.8837560039006427.
The precision of the model is 0.8702997781928496, using weighted average.
The recall of the model is 0.8837560039006427, using weighted average.
The f1-score of the model is 0.8694969376601162, using weighted average.


In [ ]:
#The accuracy of the model is 0.8837560039006427.
#The precision of the model is 0.8702997781928496, using weighted average.
#The recall of the model is 0.8837560039006427, using weighted average.
#The f1-score of the model is 0.8694969376601162, using weighted average

In [36]:
base_model.feature_importances_

array([0.33421777, 0.27947688, 0.20062442, 0.18568092])

In [ ]:
#array([0.33421777, 0.27947688, 0.20062442, 0.18568092])


In [45]:
rf = RandomForestClassifier(n_estimators=10,random_state=42)
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, scoring='accuracy')# Fit the random search model
rf_random.fit(X_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END bootstrap=True, criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2; total time=   6.0s
[CV] END bootstrap=True, criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2; total time=   5.5s
[CV] END bootstrap=True, criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2; total time=   5.8s
[CV] END bootstrap=False, criterion=entropy, max_depth=50, max_features=auto, min_samples_leaf=1, min_samples_split=2; total time=   4.7s
[CV] END bootstrap=False, criterion=entropy, max_depth=50, max_features=auto, min_samples_leaf=1, min_samples_split=2; total time=   4.6s
[CV] END bootstrap=False, criterion=entropy, max_depth=50, max_features=auto, min_samples_leaf=1, min_samples_split=2; total time=   5.2s
[CV] END bootstrap=False, criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=

RandomizedSearchCV(cv=3,
                   estimator=RandomForestClassifier(n_estimators=10,
                                                    random_state=42),
                   n_iter=100,
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['gini', 'entropy'],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10]},
                   random_state=42, scoring='accuracy', verbose=2)

In [52]:
results = pd.DataFrame(rf_random.cv_results_)

In [71]:
results.sort_values('rank_test_score', inplace=True) 

In [82]:
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
89       5.622437      0.308862         1.062451        0.026260   
99       5.592264      0.274193         1.085084        0.036510   
12       4.442567      0.224793         0.903339        0.013086   
95       5.489658      0.055350         1.031860        0.017192   
13       4.797953      0.308969         1.104418        0.118015   
..            ...           ...              ...             ...   
20       5.322373      0.028304         1.149573        0.005675   
74       4.889700      0.039135         1.045399        0.009774   
21       5.539213      0.702590         1.086522        0.042307   
77       5.294918      0.207141         1.017829        0.007029   
71       5.144406      0.069506         1.011127        0.015820   

   param_min_samples_split param_min_samples_leaf param_max_features  \
89                      10                      1               log2   
99                       5                      1               log2   
12                       5                      1               auto   
95                       5                      1               auto   
13                      10                      2               log2   
..                     ...                    ...                ...   
20                       5                      4               log2   
74                      10                      1               auto   
21                      10                      1               log2   
77                       2                      4               log2   
71                       5                      1               log2   

   param_max_depth param_criterion param_bootstrap  \
89              80            gini           False   
99            None            gini           False   
12            None            gini           False   
95              60            gini           False   
13              20            gini           False   
..             ...             ...             ...   
20              10         entropy           False   
74              10         entropy           False   
21              10         entropy           False   
77              10            gini           False   
71              10            gini           False   

                                               params  split0_test_score  \
89  {'min_samples_split': 10, 'min_samples_leaf': ...           0.889203   
99  {'min_samples_split': 5, 'min_samples_leaf': 1...           0.889191   
12  {'min_samples_split': 5, 'min_samples_leaf': 1...           0.889191   
95  {'min_samples_split': 5, 'min_samples_leaf': 1...           0.889191   
13  {'min_samples_split': 10, 'min_samples_leaf': ...           0.889214   
..                                                ...                ...   
20  {'min_samples_split': 5, 'min_samples_leaf': 4...           0.888633   
74  {'min_samples_split': 10, 'min_samples_leaf': ...           0.888731   
21  {'min_samples_split': 10, 'min_samples_leaf': ...           0.888731   
77  {'min_samples_split': 2, 'min_samples_leaf': 4...           0.882455   
71  {'min_samples_split': 5, 'min_samples_leaf': 1...           0.882889   

    split1_test_score  split2_test_score  mean_test_score  std_test_score  \
89           0.882747           0.862528         0.878159        0.011363   
99           0.882738           0.862540         0.878156        0.011353   
12           0.882738           0.862540         0.878156        0.011353   
95           0.882738           0.862540         0.878156        0.011353   
13           0.882718           0.862531         0.878155        0.011361   
..                ...                ...              ...             ...   
20           0.882374           0.862433         0.877813        0.011172   
74           0.882368           0.861684         0.877594        0.011547   
21           0.882368           0.861684         0.877594        0.

In [54]:
rf_random.best_params_

{'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_features': 'log2',
 'max_depth': 80,
 'criterion': 'gini',
 'bootstrap': False}

In [ ]:
#{'min_samples_split': 10,
# 'min_samples_leaf': 1,
# 'max_features': 'log2',
# 'max_depth': 80,
# 'criterion': 'gini',
# 'bootstrap': False}

In [55]:
best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, X_test, y_test)

The accuracy of the model is 0.8837196625096153.
The precision of the model is 0.870227155088374, using weighted average.
The recall of the model is 0.8837196625096153, using weighted average.
The f1-score of the model is 0.869462885411546, using weighted average.


In [ ]:
#The accuracy of the model is 0.8837196625096153.
#The precision of the model is 0.870227155088374, using weighted average.
#The recall of the model is 0.8837196625096153, using weighted average.
#The f1-score of the model is 0.869462885411546, using weighted average.

In [56]:
print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))

Improvement of -0.00%.


In [57]:
best_random.feature_importances_

array([0.34756019, 0.272267  , 0.20991309, 0.17025972])

In [ ]:
#array([0.34756019, 0.272267  , 0.20991309, 0.17025972])

In [58]:
from sklearn.model_selection import GridSearchCV

In [60]:
param_grid = {
    'bootstrap': [True, False],
    'max_depth': [80],
    'max_features': ['auto', 'log2'],
    'min_samples_leaf': [1],
    'min_samples_split': [10],
    'criterion': ['gini', 'entropy'],
    'n_estimators': [10, 50, 100, 200]
}

rf = RandomForestClassifier()# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2, scoring='accuracy')



In [61]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

Fitting 3 folds for each of 32 candidates, totalling 96 fits


{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': 80,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 10,
 'n_estimators': 100}

In [ ]:
#{'bootstrap': True,
# 'criterion': 'gini',
# 'max_depth': 80,
# 'max_features': 'log2',
# 'min_samples_leaf': 1,
# 'min_samples_split': 10,
# 'n_estimators': 100}

In [62]:
best_grid = grid_search.best_estimator_
grid_accuracy = evaluate(best_grid, X_test, y_test)

The accuracy of the model is 0.8837438901036335.
The precision of the model is 0.8702337060701957, using weighted average.
The recall of the model is 0.8837438901036335, using weighted average.
The f1-score of the model is 0.8694810225054729, using weighted average.


In [ ]:
#The accuracy of the model is 0.8837438901036335.
#The precision of the model is 0.8702337060701957, using weighted average.
#The recall of the model is 0.8837438901036335, using weighted average.
#The f1-score of the model is 0.8694810225054729, using weighted average.

In [63]:
print('Improvement of {:0.2f}%.'.format( 100 * (grid_accuracy - base_accuracy) / base_accuracy))

Improvement of -0.00%.


In [64]:
best_grid.feature_importances_

array([0.37183513, 0.23795614, 0.21980817, 0.17040056])

In [ ]:
#array([0.37183513, 0.23795614, 0.21980817, 0.17040056])

In [65]:
results2 = pd.DataFrame(grid_search.cv_results_)

In [73]:
results2.sort_values('rank_test_score', inplace=True) 

In [81]:
results2

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
6      125.946505      3.968314        18.941077        0.497318   
8       10.892582      0.170529         1.887396        0.029840   
22     128.217235      2.757529        19.095713        0.787140   
18     125.280601      2.656169        19.480678        0.452778   
21      61.653585      1.689483         9.228623        0.245591   
1       70.502050      2.228280        10.422440        0.702287   
26     118.634010      2.502314        18.975838        0.971527   
15     200.244801      5.990138        36.137974        0.865260   
27     245.315382     15.171571        50.878374        2.967358   
25      57.455302      2.399670         8.853323        0.074098   
30     143.352617      3.125549        22.047759        0.118169   
31     214.547997     12.529374        26.057300        6.516931   
5       62.001744      0.277429         9.305335        0.161544   
7      236.642240      6.958101        34.247006        0.477062   
24      10.900238      0.124327         1.965770        0.167616   
10     100.827381      0.700864        16.503674        0.035421   
28      11.491082      0.078826         1.996542        0.122317   
14     100.204967      1.063114        16.528338        0.024925   
23     258.502000      2.794005        38.275863        1.894499   
11     198.222073      3.279270        33.159817        0.134529   
29      68.059342     10.161416        11.874310        1.860975   
19     248.491728      4.638014        37.493946        1.220152   
2      125.587602      5.938134        18.450699        0.140114   
17      62.084044      3.306642         9.553526        0.453435   
3      248.985232      3.715762        36.598385        0.431953   
13      50.016021      2.044854         8.586666        0.220536   
12       9.871407      0.161637         1.757893        0.001213   
20      12.495811      0.098549         1.988325        0.079924   
16      11.141753      0.275464         1.763299        0.009784   
9       50.474295      2.343824         8.521028        0.253721   
4       12.252040      0.261922         1.917042        0.035070   
0       16.302798      0.308872         2.733813        0.075780   

   param_bootstrap param_criterion param_max_depth param_max_features  \
6             True            gini              80               log2   
8             True         entropy              80               auto   
22           False            gini              80               log2   
18           False            gini              80               auto   
21           False            gini              80               log2   
1             True            gini              80               auto   
26           False         entropy              80               auto   
15            True         entropy              80               log2   
27           False         entropy              80               auto   
25           False         entropy              80               auto   
30           False         entropy              80               log2   
31           False         entropy              80               log2   
5             True            gini              80               log2   
7             True            gini              80               log2   
24           False         entropy              80               auto   
10            True         entropy              80               auto   
28           False         entropy              80               log2   
14            True         entropy              80               log2   
23           False            gini              80               log2   
11            True         entropy              80               auto   
29           False         entropy              80               log2   
19           False            gini              80               auto   
2             True            gini              80               auto   
17     